[package]
name = "example-rest-grpc-multiplex"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { path = "../../axum" }
futures = "0.3"
hyper = { version = "1.0.0", features = ["full"] }
prost = "0.13"
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.12" }
tonic-reflection = "0.12"
tower = { version = "0.5", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = { version = "0.12", features = ["prost"] }
