[package]
name = "example-tls-rustls"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../../.." }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tokio-rustls = "0.22.0"
hyper = { version = "0.14", features = ["full"] }
