[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { path = "../../axum" }
axum-macros = { path = "../../axum-macros" }
tokio = { version = "1.0", features = ["full"] }
