[package]
name = "example-oauth"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../../axum", features = ["headers"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
oauth2 = "4.1"
async-session = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
# Use Rustls because it makes it easier to cross-compile on CI
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
headers = "0.3"
http = "0.2"
