contact_links:
  - name: ğŸ™ Q&A (GitHub Discussions)
    url: https://github.com/tokio-rs/axum/discussions/categories/q-a
    about: Q&A all around axum usage
  - name: ğŸ’¬ Tokio Discord
    url: https://discord.gg/tokio
    about: Community chat for Tokio (axum channel is under libs)
