[package]
name = "example-tls-rustls"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../../axum" }
axum-server = { version = "0.2", features = ["tls-rustls"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
