[package]
name = "example-testing"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../../axum" }
mime = "0.3"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.2.0", features = ["trace"] }
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }
