[package]
name = "simple-router-wasm"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../../axum", default-features = false }
futures-executor = "0.3.21"
http = "0.2.7"
tower-service = "0.3.1"
