[package]
name = "example-serve-with-rama"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { path = "../../axum" }
pin-project-lite = "0.2.7"
rama = { version = "0.3.0-alpha.3", features = ["http-full", "tower"], default-features = false }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.5.2", features = ["util"] }
